name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "30 */2 * * *"
      timezone: "Europe/Moscow"
    - cron: "30 0-4,22-23 * * MON-FRI"
      timezone: "Europe/Moscow"
  issues:
    types: [opened, labeled]
  issue_comment:
    types: [created]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  check-pages-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Check for changes in the docs folder
        continue-on-error: true
        id: check_changes
        run: |
          git fetch origin main
          git diff --exit-code origin/main -- docs || echo "Changes detected in the docs folder."

      - name: Set output variable if changes are detected
        if: steps.check_changes.outcome == 'failure'
        run: echo "changes_detected=true" >> $GITHUB_ENV

  update-data:
    uses: ./.github/workflows/update.yml

  update-pages:
    needs: [check-pages-changes, update-data]
    if: (needs.check-pages-changes.outputs.changes_detected == 'true' || needs.update-data.outputs.data_updated == 'true') && github.event_name != 'pull_request'
    uses: ./.github/workflows/pages.yml

  test-pages:
    needs: [check-pages-changes, update-data]
    if: (needs.check-pages-changes.outputs.changes_detected == 'true' || needs.update-data.outputs.data_updated == 'true') && github.event_name == 'pull_request'
    uses: ./.github/workflows/test-pages.yml
