name: Schedule checker

on:
  schedule:
    - cron: "30 */2 * * *"
      timezone: "Europe/Moscow"
    - cron: "30 0-4,22-23 * * MON-FRI"
      timezone: "Europe/Moscow"
  issues:
    types: [opened, labeled]
  issue_comment:
    types: [created]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  check-update:
    name: Check & update
    uses: ./.github/workflows/update.yml

  update-pages:
    needs: check-update
    if: needs.check-update.jobs.rebuild-constants.result == 'success'
    name: Update pages
    uses: ./.github/workflows/pages.yml
