on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - run: uv sync

      - id: cache
        uses: actions/cache@v4
        with:
          path: site/**
          key: ${{ runner.os }}-pages-${{ github.sha }}

      - if: steps.cache.outputs.cache-hit != 'true'
        run: uv run mkdocs build --strict
            